* Himalaya Emacs
  Emacs front-end for the [[https://github.com/soywod/himalaya][himalaya]] email client.

  This is currently a work in progress.

** Installation

   =himalaya-emacs= will be submitted to MELPA once it is stable.

   Until then, you can easily install it using =use-package=.

   1. Clone the repository using git to your desired location.
      In this example I'll use
      =~/src/github.com/dantecatalfamo/himalaya-emacs=.
   2. Add the following =use-package= declaration to your =init.el=
      #+begin_src emacs-lisp
      (use-package himalaya
        :if (file-exists-p "~/src/github.com/dantecatalfamo/himalaya-emacs")
        :load-path "~/src/github.com/dantecatalfamo/himalaya-emacs")
      #+end_src

      This will load =himalaya-emacs= when it's available, but stop it
      from throwing errors if you haven't cloned it.

** Customization

   Most settings can be customized through the Emacs Easy Customize
   system. =M-x customize-group himalaya=

** List Messages

   =M-x himalaya= or =M-x himalaya-message-list=

   | Key   | Action           |
   |-------+------------------|
   | =n=   | Move cursor down |
   | =p=   | Move cursor up   |
   | =f=   | Forward page     |
   | =b=   | Backwards page   |
   | =j=   | Jump to page     |
   | =m=   | Switch mailbox   |
   | =R=   | Reply to message |
   | =F=   | Forward message  |
   | =w=   | Write message    |
   | =C=   | Copy message     |
   | =M=   | Move message     |
   | =D=   | Delete message   |
   | =RET= | View message     |

** Read Message

   After pressing enter on a message, you'll enter the message viewing
   mode.

   | Key | Action               |
   |-----+----------------------|
   | =a= | Download attachments |
   | =n= | Next message         |
   | =p= | Previous message     |
   | =r= | Reply to message     |
   | =f= | Forward message      |
   | =R= | View raw message     |
   | =q= | Kill buffer          |

** Reply All
   Pressing the universal argument key (=C-u= by default) before
   pressing the reply key will reply all to a message.

** Write Message

   When writing a new message or a reply, press =C-c C-c= to send it
   or =C-c C-k= to delete it.
